name: sensor_blackout_windows
description: Turn selected sensors fully off for manual timestamp windows.
perturbations:
  - name: lidar_off_window
    sensor: lidar
    type: sensor_off
    start: 1621218790.0
    end: 1621218895.0

  # - name: imu_off_window
  #   sensor: imu
  #   type: sensor_off
  #   start: 1621218800.0
  #   end: 1621218803.0

  # - name: camera_right_off_window
  #   sensor: camera_right
  #   type: sensor_off
  #   start: 1621218810.0
  #   end: 1621218815.0
