frame_id: base_link
odom_frame_id: rtabmap_odom
publish_tf: false
wait_imu_to_init: true
deskewing: true
deskewing_slerp: true
approx_sync: true
queue_size: 200
scan_cloud_max_points: 60000
Icp/PointToPlane: "true"
Icp/PointToPlaneK: "20"
Icp/Strategy: "1"
Icp/Iterations: "40"
Icp/VoxelSize: "0.15"
Icp/MaxCorrespondenceDistance: "1.0"
Icp/OutlierRatio: "0.80"
Icp/Force4DoF: "false"
Icp/MaxTranslation: "3.0"
Odom/Strategy: "1"
Odom/GuessMotion: "true"
Odom/ScanKeyFrameThr: "0.0"
